name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Job triggered by ${{ github.event_name }} event."
      - run: echo "🖥 Running on ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: node_modules/.bin/mocha-headless-chrome -f test.html --args no-sandbox
      - run: echo "🍏 Job status is ${{ job.status }}."
